### ISSUE TITLE
Is there any plan to support bytesin Python?

### ISSUE THREAD

**Issue by TsingJyujing** [mrecachinas/hexhamming#7]
Thank you for great work 👍🏼 
I'm wondering is there any plan to support bytes format? 

For example:

```python
hamming_distance(b'\xde\xad\xbe\xef', b'\xde\xad\xbe\xef')
```

**Comment by mrecachinas** [comment]
Hi @TsingJyujing -- can definitely add support for hexadecimal bytes.

**Comment by bigcat88** [comment]
Also imho, will be interesting such function for python:
`check_bytes_arrays_within_dist( byte* arrays_to_compare, int nElementsInArrays, byte* what_to_compare, int nBytesInElement, int max_dist)`
Return index of first array for which distance < max_dist, or -1 otherwise.

Like current `check_hexstrings_within_dist` with ability to compare many arrays(arg1) to one(arg=what_to_compare) to see if for specified distance there is any equality.
Thanks, for your work and library - anyway 👍

**Comment by mrecachinas** [comment]
Hi @TsingJyujing -- can you take a look at the [byte-support](https://github.com/mrecachinas/hexhamming/tree/byte-support) branch? If it looks good for you, I'm happy to clean it up a bit and push it up to PyPI. Because it has a breaking API change, I'll increment the major version to 2.0.

The breaking change is:

```
hexhamming.hamming_distance -> hexhamming.hamming_distance_string
```

This is to keep it consistent with the addition of `hexhamming.hamming_distance_bytes`. There wasn't a great way to check whether you were dealing with a hexadecimal string (e.g., `"fff"`) vs a hexadecimal bytestring (e.g., `b"\xff\x00"). Note that in the current implementation of `hexhamming.hamming_distance_bytes`, it will actually work with any string or `byte` you provide it (even characters above the ordinal value of 255).

**Comment by mrecachinas** [comment]
@bigcat88 Hi 👋 ! Happy to support that as well. I also noticed you forked my repo, so if you'd like to submit it a PR for it, I'm happy to review and pull in your PR! 😊

**Comment by TsingJyujing** [comment]
> Hi @TsingJyujing -- can you take a look at the [byte-support](https://github.com/mrecachinas/hexhamming/tree/byte-support) branch? If it looks good for you, I'm happy to clean it up a bit and push it up to PyPI. Because it has a breaking API change, I'll increment the major version to 2.0.
> 
> The breaking change is:
> 
> ```
> hexhamming.hamming_distance -> hexhamming.hamming_distance_string
> ```
> 
> This is to keep it consistent with the addition of `hexhamming.hamming_distance_bytes`. There wasn't a great way to check whether you were dealing with a hexadecimal string (e.g., `"fff"`) vs a hexadecimal bytestring (e.g., `b"\xff\x00"). Note that in the current implementation of `hexhamming.hamming_distance_bytes`, it will actually work with any string or `byte` you provide it (even characters above the ordinal value of 255).

WOW!!! Thank you sooooo much, the branch LGTM!!!!

**Comment by mrecachinas** [comment]
[v2.0.0](https://pypi.org/project/hexhamming/2.0.0/) is now up on PyPI. Also dropped Python 2 and <=3.5 support (whoops -- need to update the README with that...).

I'm going to close this issue unless there's anything else. Feel free to open another issue if you find any bugs or there's anything else you think would be useful.

@bigcat88 I'm also going to pull your request into a separate issue.
